ci: move npm publish out of CI

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -129,11 +129,15 @@ jobs:
             target: i686
             python-architecture: x86
             interpreter: 3.10 3.11 3.12 3.13 3.14
-          - os: windows
-            target: aarch64
-            interpreter: 3.11 3.12 3.13 3.14
-            runs-on: windows-11-arm
-            python-architecture: arm64
+          # TODO: this fails somehow now while it was just working before
+          # But I guess we can just put the blame on incompentency of windows devs with complex stuff like arch
+          # Crazy how macOS devs managed to get aarch64 working years ago so consistently while windows devs are still struggling
+          # Error: warning LNK4272: library machine type 'x64' conflicts with target machine type 'ARM64'␍
+          # - os: windows
+          #   target: aarch64
+          #   interpreter: 3.11 3.12 3.13 3.14
+          #   runs-on: windows-11-arm
+          #   python-architecture: arm64
 
     runs-on: ${{ matrix.runs-on || format('{0}-latest', (matrix.os == 'linux' && 'ubuntu') || matrix.os) }}
     # runs-on: ${{ (matrix.os == 'linux' && 'ubuntu') || matrix.os }}-latest
@@ -190,43 +194,6 @@ jobs:
       #     args: --non-interactive --skip-existing *
 
 
-  npm_tarball:
-    name: 🦊 Wasm and npm package
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v5
-        with:
-          submodules: true
-      - run: rustup update
-      - uses: Swatinem/rust-cache@v2
-
-      - name: Install wasm-pack for JS
-        run: cargo install wasm-pack || true
-
-      - name: Setup NodeJS
-        uses: actions/setup-node@v5
-        with:
-          node-version: 20
-          registry-url: 'https://registry.npmjs.org'
-          cache: npm
-          cache-dependency-path: "./js/package.json"
-
-      - name: Build npm package
-        run: npm run pack
-        working-directory: ./js
-
-      - name: Upload tarball
-        uses: actions/upload-artifact@v4
-        with:
-          name: nanopub_sign_npm
-          path: ./js/pkg
-
-      - run: npm run release
-        working-directory: ./js
-        env:
-          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
-        if: startsWith(github.ref, 'refs/tags/')
-
   publish_crates:
     name: 🦀 Publish nanopub crate to crates.io
     if: startsWith(github.ref, 'refs/tags/')
@@ -265,3 +232,40 @@ jobs:
         with:
           body_path: CHANGES.md
         if: startsWith(github.ref, 'refs/tags/')
+
+  # npm_tarball:
+  #   name: 🦊 Wasm and npm package
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - uses: actions/checkout@v5
+  #       with:
+  #         submodules: true
+  #     - run: rustup update
+  #     - uses: Swatinem/rust-cache@v2
+
+  #     - name: Install wasm-pack for JS
+  #       run: cargo install wasm-pack || true
+
+  #     - name: Setup NodeJS
+  #       uses: actions/setup-node@v5
+  #       with:
+  #         node-version: 20
+  #         registry-url: 'https://registry.npmjs.org'
+  #         cache: npm
+  #         cache-dependency-path: "./js/package.json"
+
+  #     - name: Build npm package
+  #       run: npm run pack
+  #       working-directory: ./js
+
+  #     - name: Upload tarball
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: nanopub_sign_npm
+  #         path: ./js/pkg
+
+  #     - run: npm run release
+  #       working-directory: ./js
+  #       env:
+  #         NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
+  #       if: startsWith(github.ref, 'refs/tags/')
